name: Release

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Tag Commit and Release to NPM
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.KARMARUNNERBOT_GITHUB_TOKEN }}
      HUSKY: 0
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn semantic-release
